import type { ImgHTMLAttributes } from "react";
import manifest from "@/lib/imageManifest.json";

type Entry = { w: number; h: number; variants: number[] };
const entries = manifest as Record<string, Entry>;

interface ResponsiveImageProps
  extends Omit<ImgHTMLAttributes<HTMLImageElement>, "src" | "srcSet" | "width" | "height"> {
  /** Original public path, e.g. "/integrations/01-salesforce.png". */
  src: string;
  /** `sizes` for the srcset, e.g. "32px". Defaults to the largest variant's width. */
  sizes?: string;
}

/**
 * <picture> with AVIF + WebP sources, srcset and intrinsic width/height (no
 * layout shift) for images listed in imageManifest.json (generated by
 * scripts/optimize-images.mjs). Anything else (remote URLs, data URIs, files
 * without variants) renders as a plain <img>.
 */
export function ResponsiveImage({ src, sizes, alt, ...rest }: ResponsiveImageProps) {
  const entry = entries[src];
  if (!entry) return <img src={src} alt={alt} {...rest} />;

  const base = src.replace(/\.png$/i, "");
  const widths = entry.variants.map((w) => ({ file: w, actual: Math.min(w, entry.w) }));
  const largest = widths[widths.length - 1];
  const srcSet = (ext: "avif" | "webp") =>
    widths.map(({ file, actual }) => `${base}-${file}.${ext} ${actual}w`).join(", ");
  const width = largest.actual;
  const height = Math.round((width * entry.h) / entry.w);
  const sizesAttr = sizes ?? `${width}px`;

  return (
    <picture>
      <source type="image/avif" srcSet={srcSet("avif")} sizes={sizesAttr} />
      <source type="image/webp" srcSet={srcSet("webp")} sizes={sizesAttr} />
      <img src={`${base}-${largest.file}.webp`} alt={alt} width={width} height={height} {...rest} />
    </picture>
  );
}
