// Self-hosts the Google Fonts the site uses (Bricolage Grotesque, Inter):
// downloads the latin + latin-ext woff2 files into public/fonts and writes
// src/fonts.css. Removes the render-blocking third-party CSS request and the
// extra DNS/TLS connections. Re-run only to change families/weights.
//
//   node scripts/fetch-fonts.mjs
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36";
const FAMILIES = [
  { slug: "bricolage-grotesque", url: "https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,200..800&display=swap" },
  { slug: "inter", url: "https://fonts.googleapis.com/css2?family=Inter:wght@400..700&display=swap" },
];
const KEEP = new Set(["latin", "latin-ext"]);

await mkdir(path.join(root, "public/fonts"), { recursive: true });
let css = "/* Generated by scripts/fetch-fonts.mjs — self-hosted Google Fonts. */\n";

for (const fam of FAMILIES) {
  const text = await (await fetch(fam.url, { headers: { "User-Agent": UA } })).text();
  const blocks = [...text.matchAll(/\/\* ([\w-]+) \*\/\s*(@font-face \{[\s\S]*?\})/g)];
  for (const [, subset, face] of blocks) {
    if (!KEEP.has(subset)) continue;
    const remote = face.match(/url\((https:[^)]+\.woff2)\)/)[1];
    const file = `${fam.slug}-${subset}.woff2`;
    const buf = Buffer.from(await (await fetch(remote)).arrayBuffer());
    await writeFile(path.join(root, "public/fonts", file), buf);
    console.log(file, Math.round(buf.length / 1024) + " KB");
    css += `\n/* ${subset} */\n${face.replace(remote, `/fonts/${file}`)}\n`;
  }
}
await writeFile(path.join(root, "src/fonts.css"), css);
